rekonnect-main/administration/urls.py
from django.urls import path, include
from .views import login, index, logout, event, push_event

app_name = 'administration'

urlpatterns = [
    path('login/', login, name='login'),
    path('', index, name='index'),
    path('logout/', logout, name='logout'),
    path('event/', event, name='event'),
    path('push/', push_event, name='push_event')
]

rekonnect-main/core/urls.py
from django.urls import path
from .views import index, HomeView, ProfileView, DonationView, UpdateUser, SaveUser, saved, EventList, GalleryView
from django.contrib.auth.decorators import login_required

app_name = 'core'

urlpatterns = [
    path('', index.as_view(), name='index'),
    path('home/', HomeView.as_view(), name='home'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('donation/', DonationView.as_view(), name='donation'),
    path('profile-update/', UpdateUser, name='profile-edit'),
    path('profile-save/', SaveUser, name='profile-save'),
    path('map/', saved, name='map'),
    path('events/', EventList.as_view(), name='events'),
    path('gallery/', GalleryView.as_view(), name='gallery'),
]

rekonnect-main/event/urls.py
from . import views
from django.urls import path

app_name = 'event'

urlpatterns = [
    
]

rekonnect-main/registration/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUp

app_name = 'registration'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUp, name='signup'),
]

rekonnect-main/rekonnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('staff/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('registration.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', include('administration.urls')),
]

rekonnect-main/administration/models.py
from django.db import models

# Create your models here.
class AdminModel(models.Model):
    username = models.CharField(unique=True, editable=True, max_length=50, primary_key=True)
    email = models.EmailField(editable=True)
    password = models.CharField(max_length=50)
    college_name = models.CharField(max_length=100)

    def __str__(self):
        return self.college_name


class Admin_userinfo(models.Model):
    username = models.ForeignKey(AdminModel, on_delete=models.CASCADE)
    stud_name = models.CharField(editable=True, max_length=50, default='')
    passout_year = models.IntegerField(default=1990)

    def __str__(self):
        return self.stud_username

rekonnect-main/event/models.py
from django.db import models

# Create your models here.

class event_notify(models.Model):
    event_name = models.CharField(max_length=50,default="")
    date = models.DateField()
    time = models.TimeField(auto_now=True)
    venue = models.CharField(max_length=50, default="")
    about = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.event_name

rekonnect-main/administration/forms.py
from django import forms
from .models import AdminModel


class AdminForm(forms.ModelForm):
    class Meta:
        model = AdminModel
        widgets = {
            'password': forms.PasswordInput(attrs={}),
        }

rekonnect-main/administration/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from .models import AdminModel
from event.models import event_notify
from django.core.mail import send_mail

logged_in = False

# Create your views here.
def login(request):
    global logged_in
    if logged_in:
        return HttpResponseRedirect(reverse('administration:index'))
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        s = AdminModel.objects.filter(username = username, email = email)
        if s.count() == 1:
            logged_in = True
            return HttpResponseRedirect(reverse('administration:index'))
    return render(request, 'admin-login.html', {})

def redirect_login(request):
    global logged_in
    if logged_in == False:
        return HttpResponseRedirect(reverse('administration:login'))

def index(request):
    redirect_login(request)
    return render(request, 'admin-index.html', {})

def logout(request):
    global logged_in
    if logged_in:
        logged_in = False
    return HttpResponseRedirect(reverse('core:index'))

def massmailer(request):
    send_mail('HELLO THIS IS SUBJECT',
              "HELLO THIS IS TesT",
              'devaryan.gfgsrm@gmail.com',
              ['ss1874@srmist.edu.in','absa0545@gmail.com', 'devaryan.gfgsrm@gmail.com'],
              fail_silently=False)

def event(request):
    return render(request, 'admin-event.html')

def push_event(request):
    if request.method == 'POST':
        name = request.POST.get('EventName', '')
        date = request.POST.get('Date', '')
        venue = request.POST.get('Venue', '')
        about = request.POST.get('caption', '')

        a = event_notify.objects.create(event_name=name, date=date, venue=venue, about=about)
        a.save()

        massmailer(request)
        return HttpResponseRedirect(reverse('administration:index'))

rekonnect-main/core/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views.generic import TemplateView, DetailView, ListView
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from registration.models import Profile
import json
from event.models import event_notify

# Create your views here.
class index(TemplateView):
    template_name = 'intro.html'

class HomeView(TemplateView):
    template_name = 'home.html'

class ProfileView(DetailView):
    model = User
    template_name = 'profile.html'

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.id)

class DonationView(TemplateView):
    template_name = 'donation.html'

def UpdateUser(request):
    return render(request, 'profile-edit.html')

def SaveUser(request):
    if request.method == 'POST':
        fname = request.POST.get('first_name', '')
        lname = request.POST.get('last_name', '')
        email = request.POST.get('email', '')
        passout_year = request.POST.get('year', '')
        reg = request.POST.get('reg', '')
        phone = request.POST.get('phone', '')
        
        profession = request.POST.get('proffesion', '')

        skills1 = request.POST.get('skill1', '')
        skills2 = request.POST.get('skill2', '')
        skills3 = request.POST.get('skill3', '')

        lat = request.POST.get('lat')
        lng = request.POST.get('lng')

        profile = Profile.objects.get(id=request.user.id)
        profile.first_name = fname
        profile.last_name = lname
        profile.passout_year = passout_year
        profile.registration_number = reg
        profile.phone = phone
        
        profile.lat = lat
        profile.lng = lng
        
        profile.skills1 = skills1
        profile.skills2 = skills2
        profile.skills3 = skills3

        profile.proffesion = profession

        profile.save()
    return HttpResponseRedirect(reverse('core:profile'))

def saved(request):
    allentries = Profile.objects.values_list('lat', 'lng')
    locations = []
    for i in allentries:
        e = {'lat': float(i[0]), 'lng': float(i[1])}
        locations.append(e)
    print(locations)
    json_loc = json.dumps(locations)
    return render(request, 'map.html', {'data':json_loc})

class EventList(ListView):
    model = event_notify
    template_name = 'events.html'

class GalleryView(TemplateView):
    template_name = 'gallery.html'

rekonnect-main/event/views.py
from django.shortcuts import render

# Create your views here.

rekonnect-main/templates/admin-event.html
{% load static %}
<html>
<head>
<title>Login Form Design</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/form-style.css' %}">
<body>
    <div class="loginbox">
    <img src="{% static 'img/Capture.png' %}" class="avatar">
        <h1>Event Push</h1>
        <form action="{% url 'administration:push_event' %}" method="POST">
            {% csrf_token %}
            <p>Event Name</p>
            <input type="text" name="EventName" placeholder="Event Name">
            <p>Event Date</p>
            <input type="date" name="Date" placeholder="Date">
            <input type="text" name="Venue" placeholder="Venue">
            <input type="text" name="caption" placeholder="Highlight The Event">
            <input type="image" src="{% static 'img/download.jfif' %}"  width="80" height="100px">
            <input type="submit" name="Push" value="Push Event">
        </form>

    </div>

</body>
</head>
</html>

<style>

    body{
    margin: 0;
    padding: 0;
    background-image: url(ooo.png) ;
    background-size: cover;
    background-position: center;
    font-family: sans-serif;
}

.loginbox{
    width: 320px;
    height: 520px;
    background: #000;
    color: #fff;
    top: 50%;
    left: 50%;
    position: absolute;
    transform: translate(-50%,-50%);
    box-sizing: border-box;
    padding: 70px 30px;
}

.avatar{
    width: 100px;
    height: 100px;
    border-radius: 50%;
    position: absolute;
    top: -50px;
    left: calc(50% - 50px);
}

h1{
    margin: 0;
    padding: 0 0 20px;
    text-align: center;
    font-size: 22px;
}

.loginbox p{
    margin: 0;
    padding: 0;
    font-weight: bold;
}

.loginbox input{
    width: 100%;
    margin-bottom: 20px;
}

.loginbox input[type="text"], input[type="password"]
{
    border: none;
    border-bottom: 1px solid #fff;
    background: transparent;
    outline: none;
    height: 40px;
    color: #fff;
    font-size: 16px;
}
.loginbox input[type="submit"]
{
    border: none;
    outline: none;
    height: 40px;
    background: #fb2525;
    color: #fff;
    font-size: 18px;
    border-radius: 20px;
}
.loginbox input[type="submit"]:hover
{
    cursor: pointer;
    background: #ffc107;
    color: #000;
}
.loginbox a{
    text-decoration: none;
    font-size: 12px;
    line-height: 20px;
    color: darkgrey;
}

.loginbox a:hover
{
    color: #ffc107;
}
</style>

rekonnect-main/templates/admin-index.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Responsive vertical menu navigation</title>
		<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:700, 600,500,400,300' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'css/admin-index.css' %}">

		<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
		<script src="https://code.highcharts.com/highcharts.js"></script>
		<script src="https://code.highcharts.com/modules/data.js"></script>
		<script src="{% static 'js/admin-index.js' %}"></script>

		<style>
			.ad {
				position: absolute;
				width: 300px;
				height: 250px;
				border: 1px solid #ddd;
				left: 50%;
				transform: translateX(-50%);
				top: 250px;
				z-index: 10;
			}
			.ad .close {
				position: absolute;
				font-family: 'ionicons';
				width: 20px;
				height: 20px;
				color: #fff;
				background-color: #999;
				font-size: 20px;
				left: -20px;
				top: -1px;
				display: table-cell;
				vertical-align: middle;
				cursor: pointer;
				text-align: center;
			}
		</style>
		<script type="text/javascript">
			$(function() {
				$('.close').click(function() {
					$('.ad').css('display', 'none');
				})
			})
		</script>

	</head>
	<body>
		<div class="header">
			<div class="logo">
				<i class="fa fa-tachometer"></i>
				<span>Reconnect</span>
			</div>
			<a href="#" class="nav-trigger"><span></span></a>
		</div>
		<div class="side-nav">
			<div class="logo">
				<i class="fa fa-tachometer"></i>
				<span>Reconnect	Admin</span>
			</div>
			<nav>
				<ul>
					<li>
						<a href="#">
							<span><i class="fa fa-user"></i></span>
							<span>Users</span>
						</a>
					</li>
					<li>
						<a href="{% url 'administration:event' %}">

							<span><i class="fa fa-tachometer"></i></span>
							<span>Add Events</span>
						</a>
					</li>
					<li class="active">
						<a href="#">
							<span><i class="fa fa-bar-chart"></i></span>
							<span>Analytics</span>
						</a>
					</li>
					<li>
						<a href="https://www.payunow.com/merchant-dashboard#/transactions">
							<span><i class="fa fa-credit-card-alt"></i></span>
							<span>Payments</span>
						</a>
					</li>
					<li>
						<a href="#">
							<span><i class="fa fa-credit-card-alt"></i></span>
							<span>List of Students</span>
						</a>
					</li>
					<li>
						<a href="#">
							<span><i class="fa fa-credit-card-alt"></i></span>
							<span>List of Alumni</span>
						</a>
					</li>
				</ul>
			</nav>
		</div>
		<div class="main-content">
			<div class="title">
				Welcome Admin. You are the pusher here, please mantain the bussiness just like Jesse Pinkman!!
			</div>
			<div class='ad'>
				<div class="close">
					<i class="ion-ios-close-empty"></i>
				</div>
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- kodhus demos -->
				<ins class="adsbygoogle"
				     style="display:inline-block;width:300px;height:250px"
				     data-ad-client="ca-pub-8408356133845039"
				     data-ad-slot="8154430505"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
			<div class="main">
				<div class="widget">
					<div class="title">Number of views</div>
					<div class="chart"></div>
				</div>
			</div>
		</div>
	</body>
</html>

rekonnect-main/templates/admin-login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Admin Login</title>
{% endblock title %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <center>
            <h2>Admin Login</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputUsername">Username</label>
                    <input type="text" class="form-control" id="inputUsername" aria-describedby="usernameHelp" name="username">
                    <small id="usernameHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small>
                </div>
                <div class="form-group">
                    <label for="inputEmail">Email address</label>
                    <input type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp" name="email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <button type="submit" class="btn btn-primary" name="submit">Login</button>
            </form>
        </center>
    </div>
</div>
{% endblock content %}

rekonnect-main/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    {% block title %}
    <title>Rekonnect</title>
    {% endblock title %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    {% block styles %}
    {% endblock styles %}

</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

rekonnect-main/templates/donation.html
{% extends "user_base.html" %}
{% load static %}

{% block title %}
<title>Donation Form</title>
{% endblock title %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form-style.css' %}">
{% endblock styles %}
    
{% block content %}
<div class="loginbox">
        <h1>Donation Form</h1>
        <form>
            <p>Name</p>
            <input type="text" name="name" placeholder="Name">
            <p>Email ID</p>
            <input type="email" name="email " placeholder="Email ID">
            <input type="text" name="event" placeholder="Event Name">
            <input type="image" src="{% static 'img/Payment_QR.png' %}"  width="80px" height="200px">
        </form>
        
    </div>
{% endblock content %}

rekonnect-main/templates/events.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/events.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    
    
        <header>
          <div class="logo-box">
            <a href="/">
              <img src="{% static 'img/Capture.png' %}"height="100",width="80"class="centre" >
            </a>
          </div>
              <div class="navbar ">
               
                <a class="active" href="{% url 'core:home' %}"><i class="fa fa-fw fa-home"></i> Home</a>
                <a href="{% url 'core:gallery' %}"><i class="fa fa-fw fa-images"></i>Gallery</a>
                <a href="{% url 'core:events' %}"><i class="fa fa-fw fa-calendar-alt"></i>Events</a>
                <a href="{% url 'core:profile' %}"><i class="fa fa-fw fa-user"></i>Profile</a>
                <a href="{% url 'core:donation' %}"><i class="fa fa-fw fa-gift"></i>Donation</a>
                <a href="{% url 'registration:logout' %}"><i class="fa fa-fw fa-sign-out-alt"></i>Logout</a>
              </div>
           
          </header>
          

          {% for i in object_list %}
          <div class="first hero">
            <img class="hero-profile-img" src="https://www.yadatov.com/wp-content/uploads/2019/10/black-gold-losange.png" alt="">
            <div class="hero-description-bk"></div>
            <div class="hero-logo">
              <img src="https://www.yadatov.com/wp-content/uploads/2019/12/Yadatov-Full-Logo-WhiteGold-square.png" style="background:black" alt="">
            </div>
            <div class="hero-description">
              <p>{{ i.about }}</p>
            </div>
            <div  class="hero-date">
              <p>{{ i.date }}</p>
            </div>
            <div class="hero-btn">
              <a href="#">{{i.event_name}}</a>
            </div>
          </div> 
          {% endfor %}

  
  </div>
</body>
</html>

rekonnect-main/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script
    type="text/javascript">window.$crisp = []; window.CRISP_WEBSITE_ID = "b3434c8a-5bd1-4415-92f2-57389800d304"; (function () { d = document; s = d.createElement("script"); s.src = "https://client.crisp.chat/l.js"; s.async = 1; d.getElementsByTagName("head")[0].appendChild(s); })();</script>
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>

<body>
  <div class="header">
    <img src="{% static 'img/Capture.png' %}" alt="logo" />
  </div>
  <div class="container">

    <div id="logo">RECONNECT</div>


    <div class="navigation-wrapper">
      <div class="navigation-button">
        <i class="fa fa-bars"></i>
      </div>
      <div class="navigation-menu">
        <ul>
          <li><a href="{% url 'core:home' %}">HOME</a></li>
          <li><a href="{% url 'core:gallery' %}">GALLERY</a></li>
          <li><a href="{% url 'core:events' %}">EVENTS</a></li>
          <li><a href="{% url 'core:profile' %}">PROFILE</a></li>
          <li><a href="{% url 'core:donation' %}">DONATION</a></li>
          <li><a href="{% url 'core:map' %}">LOCATION</a></li>
          <hr class="style1">
          <li><a href="{% url 'registration:logout' %}">LOGOUT</a></li>
        </ul>
      </div>
    </div>
    <section class="hero">
      <h1>REUNITE <br> <span> REKINDLE<br></span>REDISCOVER</h1>
    </section>
    <div id="rt-3bd5f2d2587767a30e25b662b326ce81" data-floating="true" data-side="left" data-width="400"
      data-height="400" data-image="https://img.icons8.com/officel/80/000000/comment-discussion.png"></div>
    <script src="https://rumbletalk.com/client/?BQeQ981-"></script>

  <script>
    var navButton = document.querySelector('.navigation-button');
    var navMenu = document.querySelector('.navigation-menu');
    var win = window;

    function openMenu(event) {

      navButton.classList.toggle('active');
      navMenu.classList.toggle('active');

      event.preventDefault();
      event.stopImmediatePropagation();
    }

    function closeMenu(event) {
      if (navButton.classList.contains('active')) {
        navButton.classList.remove('active');
        navMenu.classList.remove('active');
      }
    }
    navButton.addEventListener('click', openMenu);

    win.addEventListener('click', closeMenu, false);


  </script>

  <footer>
    
  </footer>

</body>

</html>

rekonnect-main/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Login</title>
{% endblock title %}


{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<script src="{% static 'js/login.js' %}"></script>  
{% endblock styles %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <img src="{% static 'img/login_big.png' %}" alt="wait" style="width: 100%;">
  <p></p>
  {{form.as_p}}
  <p></p>
  <button type="LOGIN">LOGIN</button>
  <button type="linkedin">LINKEDIN</button>
  <p></p>
  <p>Don't have an account yet? Register <a href="{% url 'registration:signup' %}">Here</a></p>
</form>  
{% endblock content %}

rekonnect-main/templates/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>SignUp</title>
{% endblock title %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
<script src="{% static 'js/signup.js' %}"></script>
{% endblock styles %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <img src="{% static 'img/register_big.png' %}" alt="wait" style="width: 100%;">
  <p></p>
  {{form.as_p}}
  <p></p>
  <button type="submit">SIGNUP</button>
  <button type="linkedin">LINKEDIN</button>
  <p></p>
  <p>Have an account already? Login <a href="{% url 'registration:login' %}">Here</a></p>
</form>
{% endblock content %}

rekonnect-main/templates/user_base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    {% block title %}
    <title>Document</title>
    {% endblock title %}

    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    {% block styles %}
    {% endblock styles %}

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="b3434c8a-5bd1-4415-92f2-57389800d304";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
  </head>
<body>

    <header>
        <div class="container">
          <div class="logo-box">
            <a href="/">
              <img src="{% static 'img/Capture.png' %}"height="100",width="80"class="centre" >
            </a>
          </div>
          <nav class="navbar navbar-expand-lg">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a href="{% url 'core:home' %}">HOME</a></li>      
                    <li class="nav-item"><a href="{% url 'core:gallery' %}">GALLERY</a></li>
                    <li class="nav-item"><a href="{% url 'core:events' %}">EVENTS</a></li>
                    <li class="nav-item"><a href="{% url 'core:profile' %}">PROFILE</a></li>
                    <li class="nav-item"><a href="{% url 'core:donation' %}">DONATION</a></li>
                 </ul>

                 <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a href="{% url 'registration:logout' %}">LOGOUT</a></li>
                 </ul>
        </nav>
        </div>
      </header>

    {% block content %}
    {% endblock content %}
    
</body>
</html>